##支付记录表
CREATE TABLE `pay_order_info` (
  `series` bigint(20) NOT NULL,
  `tenant_num_id` bigint(20) DEFAULT NULL COMMENT '租户号',
  `merchant_id` bigint(20) DEFAULT NULL COMMENT '商户号',
  `sub_unit_num_id` bigint(20) DEFAULT NULL COMMENT '门店号',
  `plat_type` int(4) DEFAULT NULL COMMENT '支付渠道: 1微信 2支付宝 3预付卡',
  `out_trade_no` varchar(40) DEFAULT '' COMMENT '订单号(包括消费和退货)',
  `request_no` varchar(40) DEFAULT '' COMMENT '请求编号防重',
  `transaction_id` varchar(100) DEFAULT NULL COMMENT '第三方支付订单流水号',
  `total_fee` float(8,2) DEFAULT NULL COMMENT '发生金额',
  `trade_status` varchar(40) DEFAULT '' COMMENT '订单状态 1：成功 2 : 超时  11：支付中 5：撤销成功 6：全部退款成功 7：部分退款 9：预付款成功 10：退款失败 -97：支付错误 -98：未支付 -99：未知错误 -100：订单不存在',
  `trade_type` tinyint(4) unsigned DEFAULT NULL COMMENT '1 支付 2 退款',
  `device_info` varchar(40) DEFAULT NULL COMMENT '设备号',
  `close_sign` tinyint(4) DEFAULT '0',
  `create_dtme` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '请求时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_user_id` bigint(10) DEFAULT NULL,
  `data_sign` tinyint(4) DEFAULT '0' COMMENT '0：正式  1：测试',
  `item_body` varchar(255) DEFAULT NULL COMMENT '订单描述',
  `openid` varchar(128) DEFAULT NULL,
  `attach` varchar(2000) DEFAULT NULL,
  `cancel_sign` tinyint(4) unsigned DEFAULT '0',
  `subject` varchar(256) DEFAULT NULL COMMENT '订单标题',
  `pay_app_key` varchar(32) DEFAULT NULL,
  `create_ip` varchar(255) DEFAULT NULL,
  `trade_status_res` varchar(4000) DEFAULT NULL COMMENT '第三方支付平台返回结果',
  `channel` varchar(40) DEFAULT NULL COMMENT '来源渠道 ',
  `txndate` varchar(8) DEFAULT NULL COMMENT '交易日期 格式:YYMMDD',
  `txntime` varchar(8) DEFAULT NULL COMMENT '支付产生的时间 格式:HHMMSS',
  `tranId` varchar(5000) DEFAULT NULL COMMENT '第三方支付条码号',
  `ext1` varchar(100) DEFAULT NULL COMMENT '备用1',
  `ext2` varchar(100) DEFAULT NULL COMMENT '备用2',
  `ext3` varchar(200) DEFAULT NULL COMMENT '备用3',
  `ext4` varchar(200) DEFAULT NULL COMMENT '备用4',
  `src_out_trade_no` varchar(40) DEFAULT '' COMMENT '原订单号(退货)',
  `business_callback` varchar(200) DEFAULT '' COMMENT '业务回调url或method',
  `business_callback_status` tinyint(4) DEFAULT NULL COMMENT '业务回调状态，0 未回调，1 已回调',
  PRIMARY KEY (`series`),
  KEY `idx_tenant_num_id_out_trade_no` (`tenant_num_id`,`out_trade_no`) USING BTREE,
  KEY `idx_create_dtme` (`create_dtme`),
  KEY `uniq_out_trade_no_plat_type` (`out_trade_no`,`plat_type`),
  KEY `idx_pay_order_info_busi_call` (`trade_status`,`business_callback_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

##请求参数表
CREATE TABLE `pay_param_log` (
  `series` bigint(20) NOT NULL DEFAULT '0' COMMENT '序号（主键）',
  `out_trade_no` varchar(40) DEFAULT ' ' COMMENT '订单',
  `request_params` text COMMENT '请求参数',
  `response_params` text COMMENT '相应参数',
  `channel` varchar(40) DEFAULT ' ' COMMENT '请求渠道',
  `request_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '请求时间',
  `response_date` datetime DEFAULT NULL COMMENT '响应时间',
  `response_code` varchar(40) DEFAULT ' ' COMMENT '系统返回值',
  `response_msg` varchar(200) DEFAULT ' ' COMMENT '系统返回消息',
  `thread_id` varchar(40) DEFAULT ' ' COMMENT '线程ID',
  `ip` varchar(40) DEFAULT NULL COMMENT '处理服务器的IP',
  `tenant_num_id` bigint(20) DEFAULT '0' COMMENT '租户ID',
  `plat_type` smallint(6) DEFAULT '0',
  `operat_type` varchar(40) DEFAULT '',
  `pay_app_key` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`series`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

##支付类型表
CREATE TABLE `ex_arc_pay_type` (
  `series` bigint(20) NOT NULL DEFAULT '0',
  `tenant_num_id` int(11) NOT NULL DEFAULT '0' COMMENT '租户ID',
  `pay_type_id` int(11) NOT NULL DEFAULT '0' COMMENT '付款方式ID',
  `pay_type_name` varchar(60) DEFAULT ' ' COMMENT '付款方式名称',
  `aotosign` tinyint(4) DEFAULT '1' COMMENT '0跟第三方交互（支付宝微支付等），1直接完成（现金等），2不跟第三方交互但是要交易中（银联刷卡等）',
  `create_dtme` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `last_updtme` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '最后更新时间',
  `create_user_id` bigint(20) DEFAULT '1' COMMENT '用户',
  `last_update_user_id` bigint(20) DEFAULT '1' COMMENT '更新用户',
  `cancelsign` char(1) DEFAULT 'N' COMMENT '删除',
  `insertdata` char(1) DEFAULT 'Y' COMMENT '新增',
  `updatedata` char(1) DEFAULT 'N' COMMENT '更新',
  `backsign` tinyint(4) DEFAULT '0' COMMENT '标识付款方式在退货时，是否支持参与退现金金额的计算，1为参与，0为不参与',
  `ec_type_id` varchar(10) DEFAULT ' ' COMMENT '跨境购电商付款方式',
  `withdrawals_sign` tinyint(4) DEFAULT '0' COMMENT '是否支持提现',
  `is_real` tinyint(2) DEFAULT '0' COMMENT '是否真实付款，0否，1是',
  `data_sign` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0: 正式  1：测试',
  `fi_share_sign` tinyint(4) DEFAULT '0' COMMENT '财务开票价标志，0不参与，1参与',
  `cust_share_sign` tinyint(4) DEFAULT '0' COMMENT '消费者开票价标志，0不参与，1参与',
  `orn_num_id` int(1) DEFAULT '-1' COMMENT '-1时为所有渠道，积分支付时，对应的渠道，0表示GB积分支付的渠道，11表示MC积分支付的渠道',
  `interface_sign` int(1) DEFAULT '0' COMMENT '界面交互标识，0无交互，1输入交易流水，2积分交互,3刷卡机跟机器交互 ',
  `repeat_sign` int(1) DEFAULT '0' COMMENT '销售时是否允许多次付款，0否，1是',
  `payment_channel` int(11) DEFAULT NULL,
  `frozen` varchar(10) DEFAULT NULL COMMENT '是否禁用',
  `is_third_invoice` char(255) DEFAULT '0' COMMENT '0：非第三方开票，1： 是第三方开票',
  `limit_num` int(4) DEFAULT '0' COMMENT '限制次数',
  `installment_type` tinyint(4) DEFAULT '0' COMMENT '支付方式是否可分期 1是，0否',
  `pay_type_logo` varchar(100) DEFAULT ' ' COMMENT '支付方式图标',
  `open_return_type` tinyint(4) DEFAULT '1' COMMENT '是否支持退货： 1是，0否',
  `return_type` tinyint(4) DEFAULT '1' COMMENT '退货类型： 1 部分退货(包含整单退)，2 整单退货',
  `installment_line` decimal(18,2) DEFAULT '0.00' COMMENT '最低分期满额度',
  PRIMARY KEY (`tenant_num_id`,`pay_type_id`,`data_sign`,`series`),
  KEY `ux_ex_arc_pay_type` (`series`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
