#topic
CREATE TABLE `platform_mq_topic` (
  `series` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `msg_id` bigint(20) NOT NULL COMMENT '自定义唯一业务主键',
  `topic_alias` varchar(150) DEFAULT NULL,
  `topic` varchar(150) NOT NULL COMMENT '消息主题(不能为空,与tag构成唯一主键)',
  `tag_alias` varchar(150) DEFAULT NULL,
  `tag` varchar(150) NOT NULL DEFAULT '0',
  `from_system` varchar(20) NOT NULL COMMENT '消息来源什么系统',
  `create_date_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `create_user_name` varchar(10) NOT NULL COMMENT '创建人名称',
  `remark` varchar(100) DEFAULT NULL COMMENT '备注说明信息',
  `consumer_type` smallint(6) NOT NULL DEFAULT '0' COMMENT '消费者类型 1 表示dubbo 2 表示http',
  `consumer_series` bigint(20) DEFAULT NULL COMMENT '消费者编号',
  `consumer_instance_count` smallint(6) DEFAULT '1' COMMENT '消费者实例数',
  `cancelsign` varchar(1) DEFAULT 'N',
  `consumer_interval` bigint(20) DEFAULT '0' COMMENT '消费者拉取数据间隔，单位毫秒，默认0',
  `retries` int(10) DEFAULT '3' COMMENT '重试次数',
  `retries_test` int(10) DEFAULT '3' COMMENT '测试环境的重试次数',
  `retries_develop` int(10) DEFAULT '3' COMMENT '开发环境下的重试次数',
  `task_target` varchar(30) DEFAULT NULL COMMENT '这是每个任务的消费指标，用来扩充服务器用',
  `is_distinct` varchar(2) DEFAULT 'N' COMMENT '是否去重',
  `mess_batch_num` int(5) DEFAULT '1' COMMENT '消息批量拿取数量默认1',
  `consumer_thread_min` int(4) DEFAULT '3' COMMENT '消费者最小线程数',
  `consumer_thread_max` int(4) DEFAULT '5' COMMENT '消费者最大线程数',
  `tenant_num_id` bigint(7) NOT NULL DEFAULT '1' COMMENT '租户ID',
  `wether_order_mess` varchar(1) DEFAULT 'N' COMMENT '是否顺序消费',
  `retry_interval` varchar(90) DEFAULT '' COMMENT '重试间隔(只需要输入以下集合中延时时间的index即可)0，1s，5s，10s，30s，1m，2m，3m，4m，5m，6m，7m，8m，9m，10m，20m，30m，1h，2h',
  `system_num_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '系统ID',
  `wether_insertdb` varchar(1) DEFAULT 'Y' COMMENT '是否插入本地数据库',
  `correct_codes` varchar(140) DEFAULT '' COMMENT '业务项目返回这些code视为消费正确',
  `mq_queue` bigint(10) DEFAULT '8' COMMENT '队列数量',
  `wether_handle_failedmess` varchar(1) DEFAULT 'Y' COMMENT '是否处理消费失败的消息',
  `retry_max` bigint(1) DEFAULT '20' COMMENT '最大重试次数',
  `zk_data_sign` bigint(1) DEFAULT '0' COMMENT 'zk的dataSign,默认都是0，如果类似Pos这样的项目发消息没有dataSign需要用这个字段去区分zk的地址，0为线上地址，1为线下地址',
  `mq_namesrv` varchar(80) DEFAULT NULL COMMENT 'mq路由',
  `consumer_ip` varchar(80) DEFAULT NULL COMMENT '消费者IP',
  `consumer_distinct` char(1) DEFAULT 'Y',
  `consumer_pull_delay` bigint(10) DEFAULT NULL COMMENT '消费端拉取延时(单位毫秒)最多延时一分钟',
  `datasouce_name` varchar(100) DEFAULT '' COMMENT '数据源名称',
  `_mycat_op_time` bigint(20) DEFAULT NULL COMMENT '全局表保存修改时间戳的字段名',
  PRIMARY KEY (`series`),
  UNIQUE KEY `platform_mq_topic_uq1` (`topic`,`tag`),
  UNIQUE KEY `platform_mq_topic_uq2` (`msg_id`),
  KEY `platform_mq_topic_uq3` (`tag`)
) ENGINE=InnoDB AUTO_INCREMENT=202007291410431236 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

#dubbo消费者
CREATE TABLE `platform_mq_dubbo_consumer` (
  `series` bigint(20) NOT NULL,
  `service_name` varchar(500) DEFAULT NULL COMMENT '消费者dubbo服务类 包名.类名',
  `method_name` varchar(100) DEFAULT NULL COMMENT 'dubbo服务方法',
  `param_entity` varchar(150) DEFAULT NULL COMMENT 'dubbo方法的入参实体 包名.类名',
  `create_user_name` varchar(20) DEFAULT NULL COMMENT '创建人名称',
  `create_date_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `zk_adr_test` varchar(300) DEFAULT NULL COMMENT '测试dubbo方法的zk地址',
  `zk_adr` varchar(300) DEFAULT NULL COMMENT 'zookeeper 地址 ip加端口',
  `cancelsign` varchar(1) DEFAULT 'N',
  `direct_adr` varchar(50) DEFAULT NULL COMMENT 'dubbo直连时的配置地址',
  `version` varchar(500) DEFAULT NULL COMMENT '版本',
  `retries` int(10) DEFAULT NULL COMMENT '重试次数',
  `zk_adr_develop` varchar(300) DEFAULT NULL COMMENT '准正式zk地址',
  `dubbo_group` varchar(40) DEFAULT NULL COMMENT 'dubbo的groupID，相当于指定具体的实例（也就是多例）',
  `remark` varchar(40) DEFAULT '' COMMENT '备注',
  `_dble_op_time` bigint(20) DEFAULT NULL COMMENT 'field for checking consistency',
  `_mycat_op_time` bigint(20) DEFAULT NULL COMMENT '全局表保存修改时间戳的字段名',
  PRIMARY KEY (`series`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

#http消费者
CREATE TABLE `platform_mq_http_consumer` (
  `series` bigint(20) NOT NULL,
  `url` varchar(500) DEFAULT NULL COMMENT '消费者dubbo服务类 包名.类名',
  `url_test` varchar(500) DEFAULT NULL COMMENT '消费者dubbo服务类 包名.类名',
  `param_name` varchar(50) DEFAULT NULL COMMENT 'dubbo服务方法',
  `create_user_name` varchar(20) DEFAULT NULL COMMENT '创建人名称',
  `create_date_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `cancelsign` varchar(1) DEFAULT 'N',
  `remark` varchar(40) DEFAULT '' COMMENT '备注',
  `url_develop` varchar(500) DEFAULT NULL COMMENT '消费者dubbo服务类 包名.类名',
  `_dble_op_time` bigint(20) DEFAULT NULL COMMENT 'field for checking consistency',
  `_mycat_op_time` bigint(20) DEFAULT NULL COMMENT '全局表保存修改时间戳的字段名',
  PRIMARY KEY (`series`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

#消息发送日志表
CREATE TABLE `sys_rocket_mq_send_log` (
  `series` bigint(18) NOT NULL COMMENT '行号',
  `message_id` varchar(100) DEFAULT '' COMMENT 'rocket mq 自身产生消息id',
  `message_key` varchar(100) DEFAULT '' COMMENT '业务系统生成的唯一序号',
  `message_body` mediumtext,
  `message_topic` varchar(50) DEFAULT '' COMMENT '消息主题',
  `message_tag` varchar(50) DEFAULT '' COMMENT '消息标签',
  `message_name_addr` varchar(100) DEFAULT '' COMMENT 'mq的命名服务器地址',
  `producer_name` varchar(100) DEFAULT '' COMMENT '消息生产者名称',
  `create_dtme` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `last_updtme` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最后更新时间',
  `create_user_id` bigint(18) unsigned DEFAULT '1' COMMENT '创建用户',
  `last_update_user_id` bigint(18) unsigned DEFAULT '1' COMMENT '更新用户',
  `cancelsign` char(1) DEFAULT 'N' COMMENT '删除',
  `fail_detail` text COMMENT '消息失败的原因',
  `tenant_num_id` int(11) unsigned DEFAULT '0' COMMENT '租户ID',
  `data_sign` tinyint(4) unsigned DEFAULT '0' COMMENT '0: 正式  1：测试',
  `workflow_id` bigint(20) DEFAULT NULL COMMENT '需要被流程管理流程设计id',
  `instance_id` bigint(20) DEFAULT NULL COMMENT '流程实例id',
  `step_id` int(20) DEFAULT NULL COMMENT '步骤id',
  `from_system` varchar(100) DEFAULT '' COMMENT '来源系统名称',
  `msg_status` int(5) unsigned DEFAULT '0' COMMENT '消息状态：1 发送成功，2 预发送，3 发送失败，4,取消发送',
  `consumer_success` varchar(2) DEFAULT '' COMMENT '消费成功标识，默认是空，成功变成Y,失败是N',
  `retry_times` bigint(7) DEFAULT '0' COMMENT '重试次数',
  `consumer_success_time` datetime DEFAULT NULL COMMENT '消费成功时间',
  `task_target` varchar(30) DEFAULT NULL COMMENT '这是每个任务的消费指标，用来扩充服务器用',
  `order_mess_flag` bigint(2) DEFAULT '0' COMMENT '顺序消息表示，为1就是顺序消息，0是正常消息',
  `response_detail` text COMMENT '返回值详细信息',
  `next_retry_interval` varchar(12) DEFAULT NULL COMMENT '下一次的重试间隔',
  `client_ip` varchar(30) DEFAULT NULL COMMENT '客户端IP',
  PRIMARY KEY (`series`),
  KEY `ix_sys_rocket_mq_send_log_1` (`message_key`),
  KEY `ix_sys_rocket_mq_send_log_2` (`message_topic`),
  KEY `ix_sys_rocket_mq_send_log_3` (`message_tag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='消息发送日志';

#消息发送历史
CREATE TABLE `sys_rocket_mq_send_log_history` (
  `series` bigint(18) NOT NULL COMMENT '行号',
  `message_id` varchar(100) DEFAULT '' COMMENT 'rocket mq 自身产生消息id',
  `message_key` varchar(100) DEFAULT '' COMMENT '业务系统生成的唯一序号',
  `message_body` mediumtext,
  `message_topic` varchar(50) DEFAULT '' COMMENT '消息主题',
  `message_tag` varchar(50) DEFAULT '' COMMENT '消息标签',
  `message_name_addr` varchar(100) DEFAULT '' COMMENT 'mq的命名服务器地址',
  `producer_name` varchar(100) DEFAULT '' COMMENT '消息生产者名称',
  `create_dtme` datetime DEFAULT NULL COMMENT '创建时间',
  `last_updtme` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最后更新时间',
  `create_user_id` bigint(18) unsigned DEFAULT '1' COMMENT '创建用户',
  `last_update_user_id` bigint(18) unsigned DEFAULT '1' COMMENT '更新用户',
  `cancelsign` char(1) DEFAULT 'N' COMMENT '删除',
  `fail_detail` text COMMENT '消息失败的原因',
  `tenant_num_id` int(11) unsigned DEFAULT '0' COMMENT '租户ID',
  `data_sign` tinyint(4) unsigned DEFAULT '0' COMMENT '0: 正式  1：测试',
  `workflow_id` bigint(20) DEFAULT NULL COMMENT '需要被流程管理流程设计id',
  `instance_id` bigint(20) DEFAULT NULL COMMENT '流程实例id',
  `step_id` int(20) DEFAULT NULL COMMENT '步骤id',
  `from_system` varchar(100) DEFAULT '' COMMENT '来源系统名称',
  `msg_status` int(5) unsigned DEFAULT '0' COMMENT '消息状态：1 发送成功，2 预发送，3 发送失败，4,取消发送',
  `consumer_success` varchar(2) DEFAULT '' COMMENT '消费成功标识，默认是空，成功变成Y,失败是N',
  `retry_times` bigint(7) DEFAULT '0' COMMENT '重试次数',
  `consumer_success_time` datetime DEFAULT NULL COMMENT '消费成功时间',
  `task_target` varchar(30) DEFAULT NULL COMMENT '这是每个任务的消费指标，用来扩充服务器用',
  `order_mess_flag` bigint(2) DEFAULT '0' COMMENT '顺序消息表示，为1就是顺序消息，0是正常消息',
  `response_detail` text COMMENT '返回值详细信息',
  `next_retry_interval` varchar(12) DEFAULT '0' COMMENT '下一次的重试间隔',
  `client_ip` varchar(30) DEFAULT '' COMMENT '客户端IP',
  `_dble_op_time` bigint(20) DEFAULT NULL COMMENT 'field for checking consistency',
  KEY `idx_sys_rocket_mq_send_log_4` (`message_key`),
  KEY `idx_sys_rocket_mq_send_log_1` (`message_topic`),
  KEY `idx_sys_rocket_mq_send_log_5` (`message_tag`),
  KEY `idx_sys_rocket_mq_send_log_2` (`msg_status`),
  KEY `idx_sys_rocket_mq_send_log_6` (`series`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='消息发送历史表';

#消费失败存储表
CREATE TABLE `sys_rocket_mq_consumer_failedlog` (
  `msg_series` bigint(20) NOT NULL COMMENT '行号',
  `type_id` bigint(3) NOT NULL COMMENT '类型表示，1为消费次数过多，2为消费时间过长',
  `create_dtme` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `already_deal` varchar(1) NOT NULL DEFAULT 'N' COMMENT '已处理N为未处理，Y为已处理',
  `data_sign` bigint(1) NOT NULL DEFAULT '1' COMMENT '线上线下标识',
  `tenant_num_id` bigint(1) NOT NULL DEFAULT '1' COMMENT '租户',
  KEY `ix_sys_rocket_mq_consumer_failedlog` (`msg_series`,`type_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='消费失败存储表';

